version: 2.1
jobs:
   master:
      environment:
         IMAGE_NAME: thortz/docker-sogebot
      docker:
         - image: circleci/buildpack-deps:stretch
      steps:
         - checkout
         - setup_remote_docker
         - run: docker build -t $IMAGE_NAME:latest .
         - run: |
            docker login -u $docker_login -p $docker_pass
            docker push thortz/docker-sogebot:latest
   version:
      environment:
         IMAGE_NAME: thortz/docker-sogebot
      docker:
         - image: circleci/buildpack-deps:stretch
      steps:
         - checkout
         - setup_remote_docker
         - run: docker build -t $IMAGE_NAME:$CIRCLE_TAG .
         - run: |
            docker login -u $docker_login -p $docker_pass
            docker push thortz/docker-sogebot:$CIRCLE_TAG
workflows:
   version: 2
   build-master:
      jobs:
         - master:
            filters:
               branches:
                  only: latest
   tagged-build:
      jobs:
         - version:
            filters:
               tags:
                  only: /^v.*/