version: 2
jobs:
  build:
    docker:
      - image: debian:9
    steps:
      - checkout
      - run: docker build -t thortz/docker-sogebot:$CIRCLE_BRANCH .
      - run: docker push thortz/docker-sogebot:$CIRCLE_BRANCH
