version: 2.1
jobs:
   test:
      environment:
         IMAGE_NAME: thortz/docker-sogebot
      docker:
         - image: circleci/buildpack-deps:stretch
      steps:
         - checkout
         - setup_remote_docker
         - run: docker build -t $IMAGE_NAME:dev .
   master:
      environment:
         IMAGE_NAME: thortz/docker-sogebot
      docker:
         - image: circleci/buildpack-deps:stretch
      steps:
         - checkout
         - setup_remote_docker
         - run: docker build -t $IMAGE_NAME:latest .
         - run: |
            docker login -u $docker_login -p $docker_pass
            docker push thortz/docker-sogebot:latest
   version:
      environment:
         IMAGE_NAME: thortz/docker-sogebot
      docker:
         - image: circleci/buildpack-deps:stretch
      steps:
         - checkout
         - setup_remote_docker
         - run: docker build -t $IMAGE_NAME:$CIRCLE_TAG .
         - run: |
            docker login -u $docker_login -p $docker_pass
            docker push thortz/docker-sogebot:$CIRCLE_TAG
   trivy:
    docker:
      - image: docker:18.09-git
    steps:
      - checkout
      - run:
          name: Build image
          command: docker build -t trivy-ci-test:${CIRCLE_SHA1} .
      - run:
          name: Install trivy
          command: |
            apk add --update curl
            VERSION=$(
                curl --silent "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | \
                grep '"tag_name":' | \
                sed -E 's/.*"v([^"]+)".*/\1/'
            )

            wget https://github.com/aquasecurity/trivy/releases/download/v${VERSION}/trivy_${VERSION}_Linux-64bit.tar.gz
            tar zxvf trivy_${VERSION}_Linux-64bit.tar.gz
            mv trivy /usr/local/bin
      - run:
          name: Scan the local image with trivy
          command: trivy --exit-code 0 --no-progress trivy-ci-test:${CIRCLE_SHA1}
workflows:
   version: 2
   build-dev:
      jobs:
         - test:
            filters:
               branches:
                  only: testing
         - trivy:
            filters:
               branches:
                  only: testing
   build-master:
      jobs:
         - master:
            filters:
               branches:
                  only: master
   build-tagged:
      jobs:
         - version:
            filters:
               tags:
                  only: /^v[0-9]+(\.[0-9]+).*/
               branches:
                  ignore: /.*/
