version: 2.1
jobs:
   test:
      environment:
         IMAGE_NAME: thortz/docker-sogebot
      docker:
         - image: circleci/buildpack-deps:stretch
      steps:
         - checkout
         - setup_remote_docker
         - run: docker build -t $IMAGE_NAME:dev .
   master:
      environment:
         IMAGE_NAME: thortz/docker-sogebot
      docker:
         - image: circleci/buildpack-deps:stretch
      steps:
         - checkout
         - setup_remote_docker
         - run: docker build -t $IMAGE_NAME:latest .
         - run: |
            docker login -u $docker_login -p $docker_pass
            docker push thortz/docker-sogebot:latest
   version:
      environment:
         IMAGE_NAME: thortz/docker-sogebot
      docker:
         - image: circleci/buildpack-deps:stretch
      steps:
         - checkout
         - setup_remote_docker
         - run: docker build -t $IMAGE_NAME:$CIRCLE_TAG .
         - run: |
            docker login -u $docker_login -p $docker_pass
            docker push thortz/docker-sogebot:$CIRCLE_TAG
   trivy:
      docker:
         - image: docker:18.09-git
      steps:
         - checkout
         - setup_remote_docker
         - run:
            name: Build image
            command: docker build -t trivy-ci-test:${CIRCLE_SHA1} .
         - run:
            name: Install trivy
            command: |
            apk add --update-cache --upgrade --update curl
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/master/contrib/install.sh | sh -s -- -b /usr/local/bin
         - run:
            name: Scan the local image with trivy (light)
            command: trivy --exit-code 0 --no-progress trivy-ci-test:${CIRCLE_SHA1}
workflows:
   version: 2
   build-dev:
      jobs:
         - test:
            filters:
               branches:
                  only: testing
         - trivy:
            filters:
               branches:
                  only: testing
   build-master:
      jobs:
         - master:
            filters:
               branches:
                  only: master
         - trivy:
            filters:
               branches:
                  only: master
   build-tagged:
      jobs:
         - version:
            filters:
               tags:
                  only: /^v[0-9]+(\.[0-9]+).*/
               branches:
                  ignore: /.*/
