version: 2
jobs:
   build:
      environment:
         IMAGE_NAME: thortz/docker-sogebot
      docker:
         - image: circleci/buildpack-deps:stretch
      steps:
         - checkout
         - setup_remote_docker
         - run: docker build -t $IMAGE_NAME:latest .
         - run: |
            docker login -u $docker_login -p $docker_pass
            docker push thortz/docker-sogebot:latest
   buildversion:
      environment:
         IMAGE_NAME: thortz/docker-sogebot
      docker:
         - image: circleci/buildpack-deps:stretch
      steps:
         - checkout
         - setup_remote_docker
         - run: docker build -t $IMAGE_NAME:$CIRCLE_BUILD_NUM .
         - run: |
            docker login -u $docker_login -p $docker_pass
            docker push thortz/docker-sogebot:$CIRCLE_BUILD_NUM
workflows:
   version: 2
   build-master:
      jobs:
         - build:
            filters:
               branches:
                  only: master
   tagged-build:
      jobs:
         - buildversion:
            filters:
               tags:
                  only: /^v.*/