version: 2
jobs:
   build:
      environment:
         IMAGE_NAME: thortz/docker-sogebot
      machine: true
      steps:
         - checkout
         - setup_remote_docker
         - run: docker build -t $IMAGE_NAME:$latest .
   publish-latest:
      steps:
         - setup_remote_docker
         - run: |
            docker login -u $docker_login -p $docker_pass
            docker push thortz/docker-sogebot:$CIRCLE_BRANCH
workflows:
   version: 2
   build-master:
      jobs:
         - build:
            filters:
               branches:
                  only: master
         - publish-latest:
            requires:
               - build
            filters:
               branches:
                  only: master